// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onnhvjtifhhqclrrswyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ubmh2anRpZmhocWNscnJzd3lkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTQyNDIsImV4cCI6MjA3Mzc5MDI0Mn0.v-TfdlT6DfCdNEGje3DzMnGEcj66zImtIERjDQwWozc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});